### ISSUE TITLE
Need  you help

### ISSUE THREAD

**Issue by Taburientelp1** [Vikassm73/Voot#1]
Hi there ,

Hope everything is good with you first of all would like to thank you for the amazing work that you have been doing, the MX Player add on works perfectly outside india , and it is really helpful for me  :)  im having issues to install this one keeps saying that the structure of that addon is incorrect, i would appreciate if you could guide me with this problem, and also would like to know if there's any way that could make work hotstar addon same as the  MX Player ?

Thanks a lot once again

Cheers

**Comment by Vikassm73** [comment]
Try now

You can try Hotstar addon from https://github.com/botallen/repository.botallen

**Comment by Taburientelp1** [comment]
perfect it works !! thanks,  yeah i did tried  the one of botallen  but the only way  it works by VPN  is there any possibility by  enabling an indian IP  like voot  it would be amazing...  thanks once again
