### ISSUE TITLE
sonyliv

### ISSUE THREAD

**Issue by jchirag0221** [Vikassm73/Voot#2]
How, I saw you were trying to play sonyliv in Kodi.
Were you able to resolve the voice issue? I mean using Kodi addon and without changing the MPD file?

Just wondering would a solution work where we download MPD file content on local file and change that audio settings to make it work?

Regards
Chirag

**Comment by Vikassm73** [comment]
No, not yet.

Downloading and playing MPD content locally is a complex solution so stop doing that. I am just waiting to get that problem solved in the Inputstream itself.

**Comment by jchirag0221** [comment]
No problem. Plus I think the new MPD needs x-playback-session-Id which doesn't work with local MPDs as it doesn't take into considerations any headers supplied.

Lets wait for Inputstream to fix it.

**Comment by Vikassm73** [comment]
Finally, it starts working using a local MPD proxy. added in my repo
